/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatistiquesRouteImport } from './routes/statistiques'
import { Route as IndexRouteImport } from './routes/index'

const StatistiquesRoute = StatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/statistiques': typeof StatistiquesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/statistiques': typeof StatistiquesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/statistiques': typeof StatistiquesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/statistiques'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/statistiques'
  id: '__root__' | '/' | '/statistiques'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StatistiquesRoute: typeof StatistiquesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistiques': {
      id: '/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof StatistiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StatistiquesRoute: StatistiquesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
